version: '3.9'

services:
  lealtad_app:
    container_name: lealtad_app
    image: lealtad-app:1.0.0
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql-db
  mysql-db:
    container_name: mysql_db
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "lealtad_schema"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
    ports:
      - 3306:3306
    volumes:
      - ./schemas:/var/lib/mysql:rw